# Generated by Django 5.0 on 2024-01-04 19:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
        ('management', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('initial_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('canceled', 'Canceled'), ('confirmed', 'Confirmed'), ('available', 'Available for Pickup'), ('retired', 'Retired'), ('completed', 'Completed'), ('returned', 'Returned'), ('expired', 'End Time Expired - Must be Returned')], default='confirmed', max_length=20)),
                ('returned_date', models.DateField(blank=True, null=True)),
                ('penalty_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('final_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.book', to_field='slug')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, to_field='username')),
            ],
        ),
    ]
