# Generated by Django 5.0 on 2024-01-12 23:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0004_credit'),
    ]

    operations = [
        migrations.CreateModel(
            name='Strike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reservation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='management.reservation')),
            ],
        ),
    ]
