# Generated by Django 5.0 on 2024-01-21 17:20

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0007_strikegroup'),
    ]

    operations = [
        migrations.AlterField(
            model_name='penalty',
            name='end_date',
            field=models.DateField(blank=True, default=datetime.date.today, help_text='Date on which the penalty will end. If is None/null, it means that the penalty is permanent.', null=True),
        ),
        migrations.AlterField(
            model_name='strikegroup',
            name='penalty',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='management.penalty'),
        ),
    ]
