# Generated by Django 4.2.9 on 2024-01-23 14:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('management', '0009_alter_penalty_user_alter_strikegroup_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='content_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='notification',
            name='object_id',
            field=models.PositiveBigIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='reservation',
            name='status',
            field=models.CharField(choices=[('canceled', 'Canceled'), ('confirmed', 'Confirmed'), ('available', 'Available for Pickup'), ('retired', 'Retired'), ('expired', 'End Time Expired - Must be Returned'), ('waiting_payment', 'Waiting payment'), ('completed', 'Completed')], default='confirmed', max_length=20),
        ),
    ]
