# Generated by Django 4.2.9 on 2024-01-23 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0010_notification_content_type_notification_object_id_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notification',
            options={'ordering': [models.Case(models.When(is_read=False, then=models.Value(0))), '-created_at']},
        ),
    ]
