# Generated by Django 4.2.9 on 2024-01-23 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0011_alter_notification_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notification',
            options={'ordering': ['is_read', '-created_at']},
        ),
    ]
