version: "3.9"

services:
  redis:
    container_name: redis
    image: redis:7.0.15-alpine
  db:
    container_name: mysql-db
    image: mysql:8.0.35-debian
    volumes:
      - mysql_data:/var/lib/mysql

    env_file:
      - .env
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
  api:
    container_name: django-api
    build:
      context: ./
      dockerfile: Dockerfile.prod
    command: gunicorn library.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - ./:/usr/src/api/
      - static_file:/home/app/api/staticfiles
      - media_file:/home/app/api/mediafiles
    expose:
      - 8000
    env_file:
      - .env
    depends_on:
      - redis
      - db

  nginx:
    container_name: nginx
    build:
      context: ./nginx
      dockerfile: Dockerfile.nginx
    ports:
      - 80:80
    volumes:
      - static_file:/home/app/api/staticfiles
      - media_file:/home/app/api/mediafiles
    depends_on:
      - api

  celery:
    container_name: celery
    build:
      context: ./
      dockerfile: Dockerfile.prod
    command: celery -A library worker -l INFO
    volumes:
      - ./:/usr/src/api/
    env_file:
      - .env
    depends_on:
      - redis
      - api

  celery-beat:
    container_name: celery-beat
    build: 
      context: ./
      dockerfile: Dockerfile.prod
    command: celery -A library beat -l info
    volumes:
      - ./:/usr/src/api/
    depends_on:
      - redis
      - api
      - celery

volumes:
  mysql_data:
  static_file:
  media_file:
